; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mp3player_i2c_audio_mod

[env]
platform = espressif32 @6.7.0
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921000
lib_deps =
	https://github.com/tzapu/WiFiManager.git

build_flags = 
            	-DCORE_DEBUG_LEVEL=3
				-DAUDIO_LOG 
				-DLV_CONF_INCLUDE_SIMPLE

[env:mp3player_bt_audio_mod]
build_flags = 
				${env.build_flags}


[env:mp3player_i2c_audio_mod]
build_flags = 
				${env.build_flags}						
				-DUSE_I2S_DAC							# GPIO4 desconectado para usar o I2S DAC
				-DI2S_BCK_PIN=4
				-DI2S_LRCLK_PIN=22
				-DI2S_DIN_PIN=27

